name: master-all-modules-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - streamlit
  - requests
  - pydantic
